### ISSUE TITLE
Tab Coloring Fails in Firefox 45.0

### ISSUE THREAD

**Issue by industriflow** [tabkit/tabkit2#101]
Problem:  All tab groups are the same color. They should be different colors.

Reproduce this problem:  
Start Firefox v45.0 with TabKit2 v 0.12.5.
Use TabKit to Group Tabs. Or open previously grouped tabs from a session.
The groups do function, close, re-open, and can be moved.
* But all tab groups are the same color. They should be different colors.

Re-Color Group doesn't work. All groups stay the same color.
Re-Color All Groups doesn't work.

Reverting to Firefox v44.0 makes the tab group coloring work normally.

I've tested this with all other Extensions disabled. Same results. I'm running Windows 7 Ultimate with all updates.

**Comment by industriflow** [comment]
By the way, I'm running Firefox 64-bit on Windows 7 64-bit. 
Tested with versions 44 and 45, as stated previously.

**Comment by Miccovin** [comment]
I can confirm this issue with my Windows 8.1-64, Firefox 45.0-64, Tab Kit 2nd Edition 0.12.5.

**Comment by gituser** [comment]
Yes, I can confirm this as well.

You can add here as well:
* New tab creation doesn't work as it was working - tab is created but you can't click on it / close it 
* Doesn't focus to new tab on ctrl+t
* Tab closing doesn't work

Would be nice if @PikachuEXE could update addons to work.

Thanks

**Comment by PikachuEXE** [comment]
Yes I know it **is** ESR now
I need several week to deal with all these problems
I only got Sunday free :S

**Comment by sniffer** [comment]
all the issues with FF45 will probably be related removal of tab grouping https://support.mozilla.org/kb/tab-groups-removal

**Comment by PikachuEXE** [comment]
Progress report:
This problem is fixed

# Tech Details (high level)
`this` in Javascript in Firefox points to different things in FF 38 & 45
Changing the reference to `window` makes them point to the same thing again

**Comment by industriflow** [comment]
PikachuEXE, thank you for fixing the tab coloring issue! I realize you need to fix issue #102 (New Tabs) first before releasing the patch.

**Comment by PikachuEXE** [comment]
I think both are fixed now
So I will release a version tonight for 45.x only
I must remove a feature in the next version which is only buggy on 45.x

38.x can just use the current version

**Comment by PikachuEXE** [comment]
Released a new version
Please test!
https://addons.mozilla.org/en-US/firefox/addon/tabkit-2nd-edition/versions/

**Comment by industriflow** [comment]
Tab coloring is working again in Firefox 45 with TK2 0.12.6. Thanks, PikachuEXE!

**Comment by PikachuEXE** [comment]
I will close this issue after some time with no further report

**Comment by M3Rocket** [comment]
This problem is fixed and working in my 45.0.1 and 0.12.6 setup. I think it can be safely closed.
