### ISSUE TITLE
Dragging tab makes other tabs 'disappear' to far right or left in vertical tabs (FF45, TK2 0.12.6)

### ISSUE THREAD

**Issue by industriflow** [tabkit/tabkit2#106]
After upgrade to Firefox 45 and TK2 0.12.6, this:  
Found problems moving tabs between groups. (I think it's different from issue #92 re expand/collapse)
How to reproduce:
1. Set up three tab groups.
2. Drag a tab from one group into another. Try dragging various tabs several times.
Problem: sometimes it works, but often the entire destination group disappears while hovering the moving tab over it (during dragging). Sometimes the group reappears. But sometimes it doesn't, and there's no way to get to those missing tabs. The space occupied by the former tab group becomes "gray."
(Also, a huge thank-you to PikachuEXE for advancing progress toward making this all work!)

I never saw this problem dragging tabs before. I was using Firefox 44 and TK2 0.12.5. Everything was working for days/weeks. Group expand/collapse was working. When I upgraded to Firefox 45 and TK2 0.12.6, I immediately found the above problems dragging a tab. 
(Windows 7 Ultimate 64-bit, all latest updates, 16 GB RAM)
I read through issue #92 re auto-expand/collapse, but that's not the problem I see now. Also, I've never used Panorama.

**Comment by industriflow** [comment]
Update:  the above problem occurs dragging a tab within the same group, and with only one group in a window.

**Comment by industriflow** [comment]
Update 2:  although tabs seem to have disappeared, in fact the tabs shifted far right or left within a column of vertical tabs. You can drag the vertical boundary edge to make the tabs wider, and the "disappeared" tabs can be seen--indented far right or left. Sometimes dragging the vertical boundary edge to make zero-width tabs (and then back) will fix the indented tabs problem.

**Comment by PikachuEXE** [comment]
o.0
It seems like a bug in calculating the offset (which is used to make it looks like a "tree")

Can you try different values in "Indent each tree level by"? 
Especially special values like 0 or 1
![screen shot 2016-04-01 at 3 55 05 pm](https://cloud.githubusercontent.com/assets/1018543/14201097/335d9578-f822-11e5-89e0-d6130b6553bc.png)

**Comment by industriflow** [comment]
I tried changing values in "Indent each tree level by." (Mine has been 4) I tried a value of 1. (0 is not possible to set.) But the behavior is the same.
Update 3:  click & "drag" a tab left or right (in vertical tabs) and many other tabs shift left or right within the vertical tab bar.

**Comment by PikachuEXE** [comment]
I am unable to reproduce this issue
From reading the code it should not do anything for the tab indention until the tab is dropped
I am using FF 45.0.1

**Comment by PikachuEXE** [comment]
Can you try with latest version?

**Comment by industriflow** [comment]
Yes, I've been meaning to give an update here. Since TK2 v. 0.12.12 on Firefox 46.0.1, I no longer have the problem with tabs "disappearing" to the side after dragging/moving a tab within in the vertical tab bar.
This is a huge improvement! Thanks for whatever coding change made this problem go away.
Separately, I should have reported since my initial complaint that I could not reproduce this in other FFox test profiles with several of my other typical extensions. I admit I never added all my usual extensions to test profiles in order to test this thoroughly. I began to wonder if my regular FFox profile was corrupted in some way that would cause this odd tab problem.
PikachuEXE, thank you for updating TK2 through several subversions since I originally reported this. As always, my hat is off to your work on TK2.

**Comment by industriflow** [comment]
For what it's worth, in the old versions the problem (tabs shifted far left or right) occurred literally while I was dragging any one tab up or down within vertical tabs. While dragging a tab, a bunch of tabs (sometimes a colored group, sometimes a bunch within a group) would "disappear" off of the left or right edge. I could make them visible by stretching the width of the vertical tab bar--then by grabbing any one of them and pulling it to the side, the whole bunch would shift back into normal alignment vertically.

**Comment by PikachuEXE** [comment]
Good to hear that!
