### ISSUE TITLE
Mouse Click and Drag disabled in FF 45.0.1 and TK2 0.12.6 on Windows.

### ISSUE THREAD

**Issue by M3Rocket** [tabkit/tabkit2#108]
Usually just a left click, hold and drag will move tabs. But this does not work with 0.12.6 and 45.0.1 for me. Makes it hard to organize and reorder tabs.

**Comment by M3Rocket** [comment]
Seems like ALL mouse click and drag functions are disabled in FF 45.0.1 as long as TK2 0.12.6 is enabled. Not just moving tabs. Click and drag works once I disable TK2.

**Comment by PikachuEXE** [comment]
What OS are you using?
I am using Windows 7

**Comment by M3Rocket** [comment]
Windows 7 here as well.

**Comment by PikachuEXE** [comment]
OK let me try that again on next Sunday
If you have other extensions installed please post them as well (you can paste screenshots)

Would be even more useful if you can reproduce with a portable
http://portableapps.com/apps/internet/firefox_portable
It should be `45.0.1` inside

**Comment by M3Rocket** [comment]
I found the culprit--it's the [Gmail Manager NG](https://addons.mozilla.org/en-US/firefox/addon/gmail-manager-ng/) that's causing the problem. Goes away once I disable that extension. Here is the bug report on their Github site: https://github.com/gmail-manager-community/gmail-manager-community/issues/29

I am closing this issue!

**Comment by PikachuEXE** [comment]
Good to know!
