### ISSUE TITLE
Cosmetic: Splitter colorization on GTK3 enabled FF46 is changed when compared to FF45 on GTK2

### ISSUE THREAD

**Issue by sniffer** [tabkit/tabkit2#109]
Hello,

after update to FF 46 (ubuntu 15.10, FF from repo) which has GTK3 support finally enabled, you can see that the vertical splitter has changed its colour and there is no clearly visible switch graphic in the middle.

Probably some style sheet update is necessary.

Never the less this is the only issue I spotted so far after update.

**Comment by PikachuEXE** [comment]
Only FF 38.x or 45.x is supported
Sorry
