### ISSUE TITLE
Full screen HTML5 video stops at bar

### ISSUE THREAD

**Issue by forteller** [tabkit/tabkit2#110]
Hey, love this extension, thank you very much!

Just wanted to let you know that when I click on the full screen button in a video on Youtube, thevideo.me etc it doesn't actually go full screen when I have this tab bar extended. It only covers the rest of the screen, but not the bar.

This is when the setting for full screen is "do nothing". But it really should be possible to set the bar to not hide when using F11, but still watch videos in full screen.

**Comment by PikachuEXE** [comment]
Both "F11" and "watch video in full screen" release the same event `fullscreen`
https://developer.mozilla.org/en-US/docs/Web/Events/fullscreen.
There is no way to know what triggers fullscreen action.

Unless Firefox can provide enough information in the event to allow Tab Kit to know what's triggering the fullscreen mode, what you requested is not implementable.

**Comment by forteller** [comment]
That's strange, because Tree Style Tabs are able to show full screen HTML5 videos while not hiding the tab bar on normal full screen.
