### ISSUE TITLE
Bookmarks Sidebar stopped working

### ISSUE THREAD

**Issue by Captainlnsano** [tabkit/tabkit2#111]
Hello,

Absolutely adore this extension, but I've ran into a strange issue since the last update, sometime today (May 11). 

I use the built-in Bookmarks sidebar and I have found that since the update, none of my bookmarks will work. Left clicking, right click > open, and even middle mouse button fail to open any of the bookmarks. The bookmarks sidebar is essentially dead. 

I've tried playing around with settings, but the only thing that has managed to make it work again was outright disabling Tabkit2. It seems very odd that TabKit would have any effect on the bookmarks sidebar, but Firefox is a strange, unruly beast.

**Comment by Captainlnsano** [comment]
Rolling back to 12.9 (which appears to be the next latest I can go back to) made the Tab Sidebar work again, so appears to be something changed/added since then.

**Comment by PikachuEXE** [comment]
OK I tested the toolbar when changing some code but not the sidebar :P
Let me fix it next Sunday

**Comment by PikachuEXE** [comment]
Can you try `0.12.13`?
It's just approved

**Comment by Captainlnsano** [comment]
My apologies, I just got back in town. Did some quick testing and seems to be in working order again. Thanks for the help!

**Comment by PikachuEXE** [comment]
Good!
