### ISSUE TITLE
FF 46.0.1 Cannot open pages from "Show All history" dialog

### ISSUE THREAD

**Issue by DShillito** [tabkit/tabkit2#112]
Hi, 
I just noticed that when running tabkit 2 I can no longer open tabs from the "Show All history" dialog, either by double clicking or selecting from the menu. If I disable Tabkit and restart the history window works again.

This is Tabkit2 Version 0.12.12 (from https://addons.mozilla.org/en-US/firefox/addon/tabkit-2nd-edition/versions/) on Windows 7 FF 46.0.1.

**Comment by conquerist** [comment]
For me it's fixed by upgrading from 0.12.12 to 0.12.13 with FF 46.0.1 on Windows 10.

**Comment by PikachuEXE** [comment]
Good :)

**Comment by DShillito** [comment]
Confirmed fixed for me also.
Cheers :)
