### ISSUE TITLE
Multi-row tab bar: arrow displayed while moving tabs points always to the uppermost row

### ISSUE THREAD

**Issue by maffe** [tabkit/tabkit2#113]
When moving a tab or a tab group in a multiline tab bar, the arrow indicating the new position points always to the first row.

**Comment by PikachuEXE** [comment]
Can you try `0.12.13`?
It's just approved

**Comment by PikachuEXE** [comment]
I will assume this is fixed after one week

**Comment by maffe** [comment]
Sorry for the delay. It is working now.
