### ISSUE TITLE
Closing inactive tab

### ISSUE THREAD

**Issue by fadeevsg** [tabkit/tabkit2#114]
When closing inactive tab the focus switches to it and then the tab is closed. As a result, the focus is on the previous tab. It became very uncomfortable to close several of the inactive tabs.

**Comment by PikachuEXE** [comment]
Can you provide the version of the extension and Firefox?
I want to make sure I am not trying to look at an already fixed issue :P

**Comment by fadeevsg** [comment]
Firefox 46.0.1 x64, Tab Kit 2nd Edition 0.12.12, Windows 7 x64.

**Comment by fadeevsg** [comment]
Firefox 46.0.1 x64, Tab Kit 2nd Edition 0.12.12, Windows 7 x64.

**Comment by PikachuEXE** [comment]
OK will look at it on next Sunday :)
Properly just some careless mistakes during the "old way to new way function patching" process for FF 45

**Comment by LookingForWayOut** [comment]
fadeevsg, not sure if my issue the same or not. Just understanding what you got going on. What I see is say I am on an my active tab. I scroll up my tab list and close a tab (active or not) with the X on it. What used to happen is just that I stay on the tab I am on and I can close any other tab by clicking X. Now, my tab focus moves to the closest active or inactive tab to the one I closed.
This the same issue you having?

**Comment by LookingForWayOut** [comment]
Also, to add, issue might be tied into unloading tabs? I am on tab 1. I right click tab 5 to unload. Normally it unloads and I am still on tab 1, but focus moves to tab 5 instead. Therefore, can not unload the tab as I am stuck on it not even able to unload. Issue not exist when I disable the addon. Might be something related to the closing issue?

**Comment by PikachuEXE** [comment]
It's already fixed and new version released
Just awaiting for approval

**Comment by PikachuEXE** [comment]
Please see if the recently approved `0.12.14` fixes this issue

**Comment by fadeevsg** [comment]
> This the same issue you having?

Yes, it's the same issue. Now it is fixed.

> Please see if the recently approved 0.12.14 fixes this issue

Thank you!
