### ISSUE TITLE
Can't find a way to preserve tab "indentation" across restarts

### ISSUE THREAD

**Issue by TheSilvus** [tabkit/tabkit2#121]
I've finally switched back to Firefox and now try to get Tabkit working (again). Everything works fine, but I can't find a way to save the group a tab is in across restarts. When restarting Firefox using the built in feature it doesn't save it, I've also tried to use the Session Manager addon and TMP, neither have been able to help.

Maybe I'm doing something completely wrong, and if so I'm sorry for taking up time, but I just don't know what to do

**Comment by PikachuEXE** [comment]
open 2 new tabs
group them manually
restart
=> not working?

**Comment by TheSilvus** [comment]
Before restart:
![tab not working 1](https://cloud.githubusercontent.com/assets/18658672/16712520/0e08db3c-468a-11e6-9d39-e35a4f1e8f92.png)
After restart:
![tab not working 2](https://cloud.githubusercontent.com/assets/18658672/16712521/13de0302-468a-11e6-8946-98c41fe67812.png)

My only installed addons are currently Tabkit, Tabkit Highlighter, Classic Theme Restorer, Session Manager and Simple Local Switcher

**Comment by PikachuEXE** [comment]
How come there is no color on tabs?

**Comment by PikachuEXE** [comment]
Also can you give the version of Tab Kit & Firefox?

**Comment by TheSilvus** [comment]
Colors haven't worked either, but the tab thing is more important currently
Firefox: 45.2.0 (ESR)
Tabkit: 0.12.15

**Comment by TheSilvus** [comment]
Also tried to disable all other plugins (except Theme Restorer and Tabkit), didn't help

**Comment by PikachuEXE** [comment]
That's really strange
I just upgraded to 45.x myself (for my main Firefox portable)
And I got no such issue
Try to reset options?

**Comment by TheSilvus** [comment]
Resetting options didn't help. I tried to reinstall Firefox but didn't delete the user data. Interestingly the indentation was saved then. I uninstalled it again, removed the %APPDATA%/Mozilla/ folder and installed again, then everything worked. Thank you for your help!
