### ISSUE TITLE
links and buttons do not click

### ISSUE THREAD

**Issue by kstavert** [tabkit/tabkit2#123]
I just "upgraded" to FF 48 (from Waterfox)

I have 7 addons installed:
FlashStopper
lastPass
nimbus screen capture
OneTab
Session Manager
Tab Kit Highlighter
Tab Kit 2nd

no matter what click on, it does 
not respond.  I click, click, click, click
and the browser jumps around and
resizes itself and I'm finally able to
click or submit or type something
in a designated spot.

I will do away with ANY/EVERY other
addon to keep TabKit2...

I stayed with a very old version of
Waterfox because TabKit2 wouldn't
work with newer versions.

I just may have to go back to old 
Waterfox... this just isn't working.

Thank you for your help
Karen

**Comment by PikachuEXE** [comment]
Can you try FF ESR 45?
https://www.mozilla.org/en-US/firefox/organizations/all/

If you are using Windows there is also a portable version
http://portableapps.com/apps/internet/firefox-portable-esr

**Comment by kstavert** [comment]
I decided to disable all of the addons
again and see if there is one that is
causing the hangup.

With TabKit 2nd disabled, links 
clicked just fine... no page resizing
or lengthy delay between click and
response.

I just renabled TabKit 2nd and the
browser is back to long delays 
between click and response and
resizing of the browser window.

please tell me what I need to do 
to make TabKit 2nd work

**Comment by M3Rocket** [comment]
The current version of TK will NOT work properly in FF 48. That's the reason why it was suggested you use FF ESR 45.3.

**Comment by kstavert** [comment]
You are AWESOME!!!!!!

TabKit 2nd works perfectly on 45

Thank you sooooooooooooooo very
much
