### ISSUE TITLE
Longshot?  tabkit version 2 for Firefox Developer Tools?

### ISSUE THREAD

**Issue by aaronELBorg** [tabkit/tabkit2#129]
Looks like firebug is now deprecated...ugh.

If I could get this add on with Firefox Developer Tools, I'd be all over it!! 

;-)

https://developer.mozilla.org/en-US/docs/Tools

Thanks for your hard work!!

**Comment by PikachuEXE** [comment]
What do you need?

**Comment by aaronELBorg** [comment]
Well, I tried installing tabkit version 2 on Firefox Developer Tools and it didn't work.  It installed ok and I see it in my list of add-ons but nothing happens with it.

It's worth mentioning that I didn't do a whole lot of poking around with it so the problem could be on my end.  Perhaps it's a simple name-spacing issue since FDT isn't plain old Firefox?

I'm just spitballin here...

**Comment by PikachuEXE** [comment]
Firefox Developer Tools is inside Firefox, instead of a separate application.
Which is why I don't understand what you need.

**Comment by aaronELBorg** [comment]
I think I messed up the name then.

I mean Firefox Developer Edition.

https://www.mozilla.org/en-US/firefox/developer/

If tabkit 2nd edition worked there, it'd be great.

Again though, maybe it does and I'm simply doing something wrong...

**Comment by PikachuEXE** [comment]
I am still trying to fix stuff for FF 52
Will release once I fixed another obvious issue

If you need Firefox Developer Edition 52 (which I aim to support) AND you are windows user
Ｙou can try to download [a portable one](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%20Developer%20Portable/52.0%20Alpha%202%20Rev%202/)

If you are MacOS / Linux user I can try to find the page for Firefox Developer Edition 52 too.

If you intend to use 53 or newer version expect TK2 to break somehow.
They breaking their internal API from time to time.
And I haven't started working on developing WebExtension version of TK2 yet

**Comment by aaronELBorg** [comment]
I'm on Linux (ubuntu).  No problem though.

I can wait.  ;-)

I still wonder how anyone else can function without vertical tabs.  Thanks again for you hard work!

**Comment by PikachuEXE** [comment]
No idea
When I look at people using whatever browser with > 10 tabs opened
I feel sad for those people
Especially Chrome got no Vertical tab option at all
