### ISSUE TITLE
TK2E 0.12.17 Not Letting FF Open Previous Sessions

### ISSUE THREAD

**Issue by LookingForWayOut** [tabkit/tabkit2#137]
Firefox 55.0.2 (32-bit)
Windows 10

Since Firefox updated, my Session Manager addon stopped working. I thought it was a problem with the addon itself. The using FF's build in restore feature, same issue. FF will open a blank tab and that is it. After further investigation and disabling all addons, I found TK2 is causing the issue. With no addons, FF will open all tabs from previous session. I enable just TK2, and all tabs are gone.

Anyone else seeing this?

**Comment by PikachuEXE** [comment]
Only ESR version is supported
Since Firefox team loves changing Firefox API which breaks extensions (no just this one)
