### ISSUE TITLE
Youtube Fullscreen Sidebar always visible [Palemoon 27]

### ISSUE THREAD

**Issue by misakitchi** [tabkit/tabkit2#142]
When i watch Youtube in fullscreen the sidebar is always visible
I have Palemoon 27
TK2 options: "Auto Collapse (Spitter Hidden)" and "Value before change"
![palemoon_2018_02_20-13_43_33](https://user-images.githubusercontent.com/9465756/36426545-37443f26-1642-11e8-894b-cb4af87a1811.jpg)

Edit:
When i right click on a tab and go in "Tab Kit" menu, sidebar disappear... but its a pain to always do this... :(

**Comment by PikachuEXE** [comment]
Try to change the option to "Value after change"?

Also what happens when you exit fullscreen

**Comment by GregordeLallo** [comment]
I've tried all the options, alas no success. Actually if I hide the toolbar, it goes completely crazy, all screen is grey and sidepanel is hidden on the right \O_o/
Anyway it was the same on regular firefox (ESR also), so I just watch high quality videos in other browsers.

**Comment by Red-Eagle-LXIX** [comment]
Just chiming in, same behavior here.  Tried all options as well.  Other options either cause a grey that cannot allow the video to view, or a grey that is replaced by the video with tabs still visible only if the sidebar grippy is moved any amount at all (otherwise remains grey).

FWIW, Fullscreen works in Basilisk with a vertical tab bar.

**Comment by PikachuEXE** [comment]
Just released a new version to fix this issue
http://addons.palemoon.org/addon/tabkit2/

Or just go to addon page and check for updates

**Comment by misakitchi** [comment]
Really Thanks!!!!
Its fixed and its working good now! :)

**Comment by PikachuEXE** [comment]
Oops sorry for really late response

- Palemoon extension update works fine for me (I test it when I released a new version)
- >How can i have a plain gray background?

![a](https://user-images.githubusercontent.com/1018543/40882958-1295bef6-6724-11e8-8bda-bd3c03efd83f.png)
Install it from https://addons.palemoon.org/addon/tabkit-tab-highlighter/

**Comment by misakitchi** [comment]
Hi! I was about to do a new issue for plain background... and i just see that you already respond to that! XD
Maybe pin this tips somewhere? :)

**Comment by PikachuEXE** [comment]
Let me post it to README

**Comment by PikachuEXE** [comment]
posted
