### ISSUE TITLE
Any chance this will get updated for ESR 60??

### ISSUE THREAD

**Issue by Spiz** [tabkit/tabkit2#147]
I really hate Firefox without this extension (and the mouse gestures add-on) - any chance it will get an update?? I would happily pay.

**Comment by PikachuEXE** [comment]
Sorry but I decided to support this extension for Pale Moon only now
Also supporting post FF 57 would require a complete rewrite (and I don't even know if it works)
Please consider switch to one of the following:
- Pale Moon (which is great for me)
- Vivaldi (Chromium based browser with vertical tab + another kind of tab grouping)
- Firefox with another extension with tab tree support

I guess I should add this in readme
