### ISSUE TITLE
Close buttons appeared on all tabs without being requested and will not go away.

### ISSUE THREAD

**Issue by GWHAYWOOD** [tabkit/tabkit2#196]
I've loved tabkit2 since the minute I installed it but it seems to have one or two quirks.

The most troublesome quirk at the moment is that every tab and every tab group was suddenly given a 'close' button.  I don't know why; perhaps it was something to do with upgrading another add-on (u-block plus?).

Having a close button on every tab and tab group is fraught because it is difficult to see which tab is active.

The menu option to give a close button only to the active tab is set.

Even if I change the menu option to something else, nothing changes.  The close buttons remain.

Even if I restart Palemoon after changing the option, nothing changes.  The close buttons will not go away.

**Comment by GWHAYWOOD** [comment]
I'm glad to see that there's been a response to my report. :)

Is there some variable which I can access somehow to stop this behaviour, even if it means some hacking?

It would be good if I could at least get back to the way things were pending a proper fix.

**Comment by PikachuEXE** [comment]
I have searched the history up until my initial commit (when copied from original project)

It turns out this option has always **not** been implemented

https://github.com/tabkit/tabkit2/commit/91d52d484be74538b029231bc40ffc1b86746be0

There are code for the option and a few lines to call functions to try to update the tab bar.
But there is **no code** for actually making close buttons visible/hidden according to preference.
That's a little surprising to me :P  

Trying to finish the feature but give me some time here.
I haven't done any dev on this for many months.

**Comment by GWHAYWOOD** [comment]
Oops!  The road to Hell is paved with good intentions. :)

Please take your time.  If I had the slightest idea where to start I might be able to help (more than forty years coding in Fortran, assembler, Pascal, C, shells, RTL/2, Perl - mostly Perl thesedays).

How do you edit comments here?  The buttons I've tried don't seem to work.

**Comment by PikachuEXE** [comment]
Edit: Pen icon
![image](https://user-images.githubusercontent.com/1018543/136166761-0097c525-f89e-4905-a03f-f664f5701a7f.png)

Here is a test version with the implementation done
[tabkit2_0.14.0-2021-10-06-042238.xpi.zip](https://github.com/tabkit/tabkit2/files/7292028/tabkit2_0.14.0-2021-10-06-042238.xpi.zip)

You need to unzip it so you get a `.xpi` file
Then simply install that file

![image](https://user-images.githubusercontent.com/1018543/136167303-4d92f877-99a7-4ba8-a0ac-6e4a797868a3.png)

**Comment by PikachuEXE** [comment]
Oh I decide not to implement the last option
"Button at end of tab strip"
As I have no idea what that means
I will remove that option before official release
