### ISSUE TITLE
Tabs which have been put into a group mysteriously disappear.

### ISSUE THREAD

**Issue by GWHAYWOOD** [tabkit/tabkit2#197]
I usually run three browser windows for three broad categories of work.

Window 1 is monitoring the status of the machines I control.
Window 2 is documents to which I routinely refer during my work.
Window 3 is security; monitoring the physical security of installations, mail systems, abuse etc.

All have muiltiple tabs open at all times.

Window 2 generally has about 50 tabs groups in it.  One of those is used for RFCs, mostly pages on ietf.org.
This tab group itself has about 50 tabs in it.

Every now and again, a number of the tabs in the RFC tab group disappears.
I don't know when this happens.  Next time I look at it, the group appears to have been reduced to only perhaps half a dozen tabs.  There doesn't seem to be a way to navigate to the missing tabs.

If I use the tab search box to find one of the missing tabs (I'll generally have a pretty good idea of what to search for in the RFCs) then the missing tabs miraculously reappear in the tab list but they are no longer in the group - they aren't in any group - so I'll have to group them all over again.

This is a little frustrating but it does not appear to cause any loss of data.

**Comment by PikachuEXE** [comment]
Do you mind sharing more details like
- browser version
- TK extensions installed with their versions
- TK settings

I use only use Palemoon for non critical stuff right now.
And I haven't experience tab disappearing issue once.
I need to be able to reproduce to investigate and maybe fix this.

Also do you mean some tabs are ungrouped sometimes or disappear completely from tab bar?

**Comment by GWHAYWOOD** [comment]
Thanks once again for your quick response.  The browser version as described by Help->About is "is Pale Moon Version: 29.4.1 (64-bit)".  I am not aware that I have any TK extensions installed, perhaps there are but if so I don't know how they got there nor how to find them.  Perhaps you can explain to me.

The tabs disappear from the tab bar.  At first I thought they were completely lost but I tried hard for some hours to find them and eventually discovered that they could be recovered by using the search box.  Yes, when they return to the tab bar they are not in any group - so for example if they had been coloured orange, the same as the other RFC tabs, when they return they are all grey, and all occupy the full width of the tab bar.  In case it's important I have the tabs in a vertical column on the left hand side of the screen.

There are a couple of improvements I could suggest for some of the wording in the menus.  They are minor changes, would you like me to put them in this thread, or start another, or send email, or...?

**Comment by GWHAYWOOD** [comment]
I seem to be unable to attach files to an issue comment - a file manager pops up, but when I select the files nothing happens - so I have put some screen shots at

http://www.jubileegroup.co.uk/misc/[1-7].gif

The shots show the TK extension page in the browser, and all the settings that I know about.

HTH

**Comment by PikachuEXE** [comment]
I do have a Palemoon portable at home but I don't remember I encountered any tab ungrouped before.
Is there anything specific about the timing or the tabs gone "missing" (ungrouped)?

I also create bookmarks for those truly important tabs as backup.
If you are using windows you might want multiple Palemoon portable for different purposes instead of multiple windows.

**Comment by PikachuEXE** [comment]
I suggest using [session manager](https://addons.palemoon.org/addon/session-manager/)
to make regular backup of your tabs and their states.

I would look into other small suggestions but I am on vacation this week.

"tab groupings revert" might be caused by bug in extension. But unless it happens every time the browser started/restarted it should not be TabKit's issue.

**Comment by GWHAYWOOD** [comment]
Thanks for the tips, I'll look into session manager and I'll try restarting the browser more often to see if that might be triggering the issue - most of the time I don't restart it from one week to the next because I'm too lazy...

Have a great vacation!

**Comment by PikachuEXE** [comment]
I remember an issue of tab groups of some tabs are not saved as they are not loaded.
That's due to tab's session/state management design by the browser and can't be fixed.
I am not sure if your issue is caused by the above reason.

**Comment by PikachuEXE** [comment]
Clicking on the date gives you an URL for the comment
![image](https://user-images.githubusercontent.com/1018543/138020189-78ed8ab1-c6e7-4085-9fd1-ac5c22ebbe5a.png)

e.g. https://github.com/tabkit/tabkit2/issues/71#issuecomment-99258288

So you want this extension to "activate" the "side effect" as if a space is entered into the search bar on browser start?
I can try that (not sure how exactly that can be done yet)

**Comment by PikachuEXE** [comment]
> "activate" the "side effect" as if a space is entered into the search bar on browser start
[tabkit2_0.14.0-2021-10-21-113243.xpi.zip](https://github.com/tabkit/tabkit2/files/7385776/tabkit2_0.14.0-2021-10-21-113243.xpi.zip)

There is no obvious issue but I cannot locally test whether the workaround works

**Comment by PikachuEXE** [comment]
Let's test this fix (now submitted as #210) for 1/2 more weeks and merge it if no other issue found (and it fixes this issue)
And then we can start testing #200

**Comment by GWHAYWOOD** [comment]
New information:

I have tried to keep tab groups safe by using the option "Protect All Tabs in Group".

When a tab group is broken by closing and re-opening the browser, sometimes tabs in a protected group are no longer protected.  It may be only a single tab or it may be several.

**Comment by PikachuEXE** [comment]
That's why this might be related to session restoring on startup (or how TK interacts with it, I am never sure which one)
Any tab lost though?

**Comment by GWHAYWOOD** [comment]
No, no tabs lost so far AFAICT.
