### ISSUE TITLE
FF19 PDF fullscreen switches tab bar to auto-hide mode

### ISSUE THREAD

**Issue by jeisner** [tabkit/tabkit2#20]
What steps will reproduce the problem?
1. configure Tab Kit to show vertical tab bar at left edge of window
2. in FF19, visit a PDF page such as http://www.education.gov.yk.ca/pdf/pdf-test.pdf
3. go to fullscreen mode by pressing F11 or clicking the Presentation Mode button
4. leave fullscreen mode by pressing Esc

The tab bar is now in some kind of auto-hide mode.  It often vanishes, and you have to put the mouse at the left edge of the window to make it temporarily pop up again.

While it's in auto-hide mode, I can't use the search feature, because when I mouse over the Search Tabs box, the whole tab bar disappears again.

The only way I've found to get it out of auto-hide mode is to use the mouse to change the width.  Seems to me there should be a global setting under Tools / Tab Kit, but I can't seem to find it.

Firefox Version (if not latest stable version):

```
Version 19.0, which has an integrated PDF viewer.
```

Operating System (if not Windows):

```
Linux Mint with MATE desktop
```

**Comment by DanielBauman88** [comment]
I'm experiencing this issue with FF41.0 and OSX 10.10.5

Resurrecting an old issue.  But it's very frustrating...

**Comment by PikachuEXE** [comment]
@DanielBauman88 
Are you using the latest version?
There is a new setting for tab bar behaviour.
Trying changing that to see what happens

**Comment by klkblake** [comment]
I just tried the new settings.

Splitter visible: Tab bar visible in full screen. When exiting full screen, tab bar goes into auto-hide mode and the close button is only visible on the current tab. Closing or opening any tab causes the close buttons to reappear on all of them. Auto-hide can be stopped by resizing the tab bar.

Splitter invisible: Tab bar visible in full screen. When exiting full screen, tab bar goes into auto-hide, but cannot be opened, even temporarily, by the mouse. You have to open a new tab to make it appear, and then it vanishes when the mouse moves off it. It cannot be resized with the mouse, nor can autohide be disabled, even by various combinations of settings + switching to and from full screen mode (I think I got auto-hide disabled for a bit by one particular combination, but I still couldn't resize it.) I had to restart firefox in the end to be able to get it back to normal.

Do nothing: Tab bar is visible in normal and full screen modes, and functions as expected.

**Comment by khmseu** [comment]
TK2 0.12.3, FF 43.0 for Ubuntu, seeing the problem. Symptoms pretty much as described. This worked for FF 39 ... something seems to have broken it.

The setting in TK changes it around, but there doesn't seem to be a good setting.
