### ISSUE TITLE
Interaction Pentadactyl and Tabkit2 on FF32

### ISSUE THREAD

**Issue by The-Flying-Guy** [tabkit/tabkit2#69]
On Firefox 32, using both Pentadactyl and Tabkit 2 (with classic theme restorer) and side tabs results in the tab sidebar only showing a single visible tab.

**Comment by PikachuEXE** [comment]
Closing since the extension seems to be discontinued
https://addons.mozilla.org/en-US/firefox/addon/pentadactyl/
