### ISSUE TITLE
jumpy tabs after tab amount exceeds vertical screen real estate

### ISSUE THREAD

**Issue by aaronELBorg** [tabkit/tabkit2#70]
I usually use a lot of tabs in the left hand side of FF.  If the amount of tabs exceeds what is visible 'above the fold', the whole stack of tabs tends to jump up and down a bit.  This is somewhat disturbing.

The fix is to simply delete the "extra" tabs until the amount doesn't go below the fold.  That's not always preferable, however.

**Comment by PikachuEXE** [comment]
Closing stale issue
