### ISSUE TITLE
Enter key broken in URL bar

### ISSUE THREAD

**Issue by ThomasMcA** [tabkit/tabkit2#72]
Tabkit 0.12.0 on Firefox 32.0.3 in 32bit Win7 breaks the Enter key in the URL bar. The Enter key is completely ignored (so is Ctrl-Enter and Alt-Enter).

If I disable Tabkit, then restart FF, the Enter key works normally.

**Comment by Marx2** [comment]
Yeah, it's broken in 35.0 too

**Comment by ThomasMcA** [comment]
In my case, it was a conflict between Tabkit and IE Tab 2. Disabling either add-on fixed the problem. I ended up disabling IE Tab 2, and loading IE when I need it.

**Comment by PikachuEXE** [comment]
Closing since this issue can kind of be "fixed" on client side
