### ISSUE TITLE
Tabs do not appear correctly.

### ISSUE THREAD

**Issue by konakova** [tabkit/tabkit2#73]
Hello ,

I use Mozilla Firefox 24.8.1. When I enter the options of Tab Kit and change where the tab bar should be shown (left or right side of the desktop) it does not appear correctly. I have to close it and open it again. 
![1](https://cloud.githubusercontent.com/assets/9217307/4632175/74cce0fc-53bb-11e4-8b57-b018c8221257.PNG)

**Comment by PikachuEXE** [comment]
Closing since no further info provided
