### ISSUE TITLE
Doesn't work very well with TabGroupsManager

### ISSUE THREAD

**Issue by deafff** [tabkit/tabkit2#78]
![image](https://cloud.githubusercontent.com/assets/6588546/5207418/882c1422-75aa-11e4-8eae-b86f0e8254ad.png)

Hi, seems that when using TabGroupsManager (https://code.google.com/p/tabgroupsmanager/), tabs are not rearranged after TGM moves them into its groups (see screenshot).
TMP works, but has its own problems, I would love to get rid of it in lieu of TK2.
Is it possible to do this somehow perhaps without rearranging it on every tabopen/tabclose, so that the FF doesn't slow down to a crawl when opening thousands of tabs at startup? I imagine it could be a problem.
Thanks.
FF 34.0, TGM latest beta 104, tabkit2 0.12.0, CTR.

**Comment by PikachuEXE** [comment]
Sorry
it's properly a style issue
But being compatible with another tab related extension is too much work for me :(
