### ISSUE TITLE
HTML5 video full-screen 

### ISSUE THREAD

**Issue by agentHEX** [tabkit/tabkit2#80]
When full-screening a html5 video, it keeps the left-tablist open, and when un-fullscreen occurs it auto-hides it. Seems like the extension is trying to do the right thing (autohide when fullscreen, and back when that's closed), but the logic is flipped. 

FF version 34.x, but I'm pretty sure it happens on earlier versions. No other tab-related extension running, Classic Theme Restorer 1.2.6.1.

I recall Flash videos worked fine, but this started happening after I uninstall flash 14.x to install 16.x (which failed, and now there's no flash pluggin so youtube and such resort to html 5).

**Comment by agentHEX** [comment]
Is there at least a hotkey to toggle the tab pane? Clicking the little button with auto-hide is a pain in the ass. Thanks.

**Comment by PikachuEXE** [comment]
Can you try out this test build?
https://bintray.com/tabkit/tabkit2/firefox_extension_package/0.12.0.dev.2015-3-14-1402/view

I have tested it in `31.1.0` and `36.0.1`, with Youtube HTML5 Video

**Comment by conquerist** [comment]
The tab pane hiding behavior in the test build looks correct to me, using `36.0.1`. Thanks for the fix!

**Comment by agentHEX** [comment]
Tried it with 36.0.1 on a few html5 sites like vimeo and comedy central, and it works great. Hides in full screen and comes back when restored.

**Comment by PikachuEXE** [comment]
`0.12.1` Released

**Comment by knary** [comment]
I am still seeing it on 0.12.3 (Firefox version 43.0.1, but I have seen it on earlier as well).

**Comment by PikachuEXE** [comment]
@knary 
Please use ESR versions to try to reproduce this bug
Only ESR versions are supported to avoid frequent changes (due to FF bugs/changes)

**Comment by agentHEX** [comment]
This is happening with ESR v45. Same issue as before, so hopefully same or similar fix will work.

**Comment by PikachuEXE** [comment]
@agentHEX 
Try changing the last option in
![screen shot 2016-04-07 at 9 04 27 am](https://cloud.githubusercontent.com/assets/1018543/14337367/c955f490-fc9f-11e5-9f29-7267f6af3a5d.png)

**Comment by agentHEX** [comment]
Changing it to "after change" worked. Thanks.
