### ISSUE TITLE
On Mac (yosemite 10.5.5): tab container is closed upon opening FF

### ISSUE THREAD

**Issue by aaronELBorg** [tabkit/tabkit2#88]
On Mac (yosemite 10.5.5) w/ FF 40.0.2.

When putting tabs on left, the tab container (of all tabs) is closed upon opening FF.

I then must click on the tiny little line to keep it open.

See image for details.

I'm wondering if there could be an option to always have the "tab sidebar" always be open if wanted.  FWIW, I only get this issue using my mac.  Don't have it in Windows or Linux.  Weird.

Thanks for this great add-on.  I really hate to be without it.

<img src="http://imageshack.com/a/img537/6981/HWUzoj.png" />
<img src="http://imageshack.com/a/img661/9071/oMYgDA.png" />

**Comment by PikachuEXE** [comment]
Please try to use 38.x to see if it's a new version issue
Firefox breaks the extension occasionally with new versions

**Comment by PikachuEXE** [comment]
Please try https://bintray.com/tabkit/tabkit2/firefox_extension_package/0.12.3.alpha-3/view
After installable you can set a new option at `Tab Bar` tab

**Comment by PikachuEXE** [comment]
Closing due to release of `0.12.3`
