### ISSUE TITLE
mac:  when opening FF, no tabs show until 'full screen' is enabled

### ISSUE THREAD

**Issue by aaronELBorg** [tabkit/tabkit2#89]
Using this add-on, and choosing to put tabs vertical tabs on left, when initially opening FF, all tabs are hidden and can't be accessed until 'full screen' is enabled (shift+command+f).
So in order to use this successfully on a mac (as this issue doesn't happen on Windows or Linux), one must:
1) enable full screen (as initial page load looks pretty bad with no tabs and downright odd display)
2) hover over left side of screen to see tabs and/or click on tiny line between the left-hand tab container to have the tab container be visible all the time (see my other issue #88)

Thank you for this add on.

Before full-screen is enabled:
<img src="http://imageshack.com/a/img538/8867/J9wdLD.png" />
After full-screen is enabled (and tiny line is clicked to keep tab container open):
<img src="http://imageshack.com/a/img661/9300/y1FgtH.png" />

**Comment by gituser** [comment]
>After full-screen is enabled (and tiny line is clicked to keep tab container open):

for me it's more annoying to get this tiny line whilst opening full-screen youtube video or any other video.

it there any possibility of eliminating it when video is playing full-screen?

**Comment by bedge** [comment]
I get this too. it's unusable with this problem.
I'm using the AIO-sidebar extension as well, which may be contributing to the problem.

**Comment by PikachuEXE** [comment]
Please try https://bintray.com/tabkit/tabkit2/firefox_extension_package/0.12.3.alpha-3/view
After installable you can set a new option at `Tab Bar` tab

@gituser You can set the new preference to hide the splitter at fullscreen.
@bedge I can't install AIO sidebar on ESR 38, so I can't test it.

**Comment by devn** [comment]
@PikachuEXE No dice, and I'm on 41.01 with no other extensions installed.

![screen shot 2015-10-07 at 1 52 27 pm](https://cloud.githubusercontent.com/assets/10421/10347689/c098e806-6cfa-11e5-968a-4fc38b09e6fc.png)

**Comment by devn** [comment]
Actually @PikachuEXE, my issue may not be the same as what @aaronELBorg is experiencing. After a fresh install of Firefox and removing my Profile, this is what I see after I restart Firefox with TabKit 2 installed. I tried the the published extension, the beta extension, and your alpha above.

**Comment by devn** [comment]
Tried on Firefox 38.0 and the same thing is happening. I could swear this was working earlier, am I forgetting to remove some preference files somewhere?

**Comment by devn** [comment]
OOPS! My bad. I see now that the `README` mentions `Classic Theme Restorer`.

Suggestion: Put that in big bold letters at the very top.

In any event, thanks so much for continuing to maintain this. The fact that this works is the only reason I'm switching back to Firefox.

**Comment by devn** [comment]
Well, as long as I've muddied up this thread: What combination of plugins do you use? Your setup looks really nice.

Do you use aging tabs, by any chance? It's a really great add-on.

**Comment by PikachuEXE** [comment]
I got a long list of extensions
So I will just give those "must have" extensions for me:

- Tab Kit (Of course)
- Other Tab Kit extensions (see README)
- Classic Theme Restorer (since Tab Kit requires)
- BarTab Lite X (highlight unloaded tab)
- Session Manager (Restore session after crash)
- pastego (open new tab, paste URL and visit with one button)


=== Separator ===
I will bold the section about `Classic Theme Restorer`. Thanks for your suggestion!

**Comment by PikachuEXE** [comment]
Closing due to release of `0.12.3`
@aaronELBorg If problem persists please reopen this
