### ISSUE TITLE
Version 0.12.3 breaks auto-expand/collapse in FF 

### ISSUE THREAD

**Issue by M3Rocket** [tabkit/tabkit2#92]
Windows FF 41.0.2 TK2 0.12.3 horizontal tabs on top

Whenever I click to expand a group, all the other groups are auto-expanded. If I collapse the group manually, then select a tab from another group, all the tabs on all groups are auto-expanded again.

Had to revert to TK2 0.12.2.1 so that I don't have the problem.

**Comment by M3Rocket** [comment]
Oh yeah--tabs go missing in 0.12.2.1, but I use Panorama to navigate to them. It's more troublesome to have all the tabs auto-expanded.

**Comment by PikachuEXE** [comment]
OK please stay on 0.12.2.1 for now
Once fixed I will release a test version for you to test

**Comment by jenslody** [comment]
Same here on Fedora 22, with FF 41.0.2.
Downgrading helps.
A workaround for the hidden tabs is to ungroup all tabs and then group them again by domain (or whatever it was before), no need to use panorama.

**Comment by jenslody** [comment]
By the way, all tabs in the expanded tab-gropus get a "+"-button, normally used to expand a group.

**Comment by M3Rocket** [comment]
@jenslody Can you please clarify your workaround? Do you mean ungroup all tabs, then start grouping them manually again? I don't group by domain (I use by Opener).

**Comment by jenslody** [comment]
@M3Rocket:
I right-click any tab,
from the context-menu I chose "Tab Kit -> Global Actions -> Ungroup All Tabs",
then I chose "Tab Kit -> Global Actions -> Group Tabs By Domain".
I don't know if it also works for "Group Tabs By Opener", but I think it's worth a try.

**Comment by barefootcoder** [comment]
Just wanted to report that I have two laptops, both running Linux Mint 17 (based on Ubuntu 14.04.1 (Trusty)).  One is running FF 37.0.2 and it *does* have this problem.  OTOH, the other is running 35.0.1 and it's perfectly fine.  Extensions are identical (or close to it), including both running TK2 0.12.3.  I haven't tried downgrading yet ... I've just been living with it.

Now, I hadn't noticed that the "hidden tabs" problem was related to this, and/or that it had been fixed by upgrading to 0.12.3, but I do admit I haven't specifically noticed it cropping up in a while.  The only time I ever have tabs come up "hidden" is when I restore a tab session (using Session Manager 0.8.1.7), and it's always all the tabs in one or more groups (but usually not every group).  AFA a workaround for that, I too have been using Panorama to get the "lost" tabs back, because I don't group by domain, so if I ungrouped all my groups, I would have to regroup them all manually and that's a *much* bigger PITA than just going into Panorama and finding them again.

Anyway, hopefully some of this info helps you track the problem(s) down.  Please let me know if I can do any further testing, provide further info, etc.  TK2 is _the_ reason I stick with FF; Chrome has _nothing_ that compares (and I just searched again to see if anything had changed).  Please keep up the good work.

**Comment by M3Rocket** [comment]
Just checking in to see if there is any progress on the resolution yet? I hate having to use Panorama to get to the missing tabs since I don't group by domain.

**Comment by PikachuEXE** [comment]
Do you guys prefer 0.12.3 behaviour or pre-0.12.3?
I can add back the workaround but it would cause #71 to happen again.

I don't have time to work on a permanent solution for both #92 (this issue) and #71 until the Lunar New Year holiday

**Comment by M3Rocket** [comment]
If both these issues are related, I think the auto-expand problem is the worst of the two. At least with the missing tabs there is a workaround by using Panorama. There is no workaround for 12.3 auto expand behavior other than going back to 12.2.1 like I have. 

So my preference is for pre-0.12.3 till you can get them both fixed.

**Comment by barefootcoder** [comment]
Agreed that #92 is worse than #71.  But I see now that 0.12.4 seems to fix #92, and I think I noticed #71 was back last time I had to bounce FF.  So it looks like that's the call you made, and I think it was the right one.

I'll comment over on #71 so I can stay notified and possibly pitch in on testing a solution, whenever you have time to work on it.  (Probably you should resolve this issue and we should move any remaining discussion over there.)

**Comment by PikachuEXE** [comment]
I try to reproduce the bug again with Firefox ESR 38.6.0 on Windows 7 but failed to
Can anyone try to reproduce it with Firefox ESR on Windows/Mac/Linux? (Normal Firefox changes too frequently so I won't support it)
I got a new version below (basically `0.12.3` with some refactor...)
[tabkit2 0.12.4+ - 2016-02-11.zip](https://github.com/tabkit/tabkit2/files/125841/tabkit2.0.12.4.-.2016-02-11.zip)

**Comment by gituser** [comment]
Hi.
Can't check this, Firefox 44.0.1 requires signing of addsons.

Also they mention in 45 ESR signing will be a requirement.

Can you sign it?

**Comment by PikachuEXE** [comment]
Arrr stupid signing ~_~
https://addons.mozilla.org/en-US/firefox/addon/tabkit-2nd-edition/versions/
See if you can can the signed version of 0.12.4+
If not I have to find a Firefox Dev version or something for testing purpose

STUPID!

**Comment by PikachuEXE** [comment]
OK found a dev version from
http://portableapps.com/apps/internet/firefox-developer-portable
[FirefoxPortableDeveloper_46.0_Alpha_2_English_online.paf.zip](https://github.com/tabkit/tabkit2/files/125853/FirefoxPortableDeveloper_46.0_Alpha_2_English_online.paf.zip)

Need to change a preference (might work on Firefox 44)
http://www.ghacks.net/2015/08/04/fix-for-installing-unsigned-add-ons-in-firefox-dev-and-nightly/

**Comment by gituser** [comment]
about signing: https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm#jpm_sign
or
http://olympia.readthedocs.org/en/latest/topics/api/signing.html

you can sign your addon and publish it here on github

your workaround works tho, but leaves unprotected field for unsigned / malicious addons for users.

about bug: I can't reproduce the bug if I got decription right on FF 44.0.1 with tabkit 0.12.4+.

**Comment by PikachuEXE** [comment]
Thanks for finding it
Let me try to sign it before I become too frustrated to give up

**Comment by PikachuEXE** [comment]
Encounter an issue with jpm
https://github.com/mozilla-jetpack/jpm/issues/458
Will try with the API

Still, stupid :S

**Comment by PikachuEXE** [comment]
After a brief read I give up on using API
I will just submit the file for auto review z_z

**Comment by gituser** [comment]
>Encounter an issue with jpm
>mozilla-jetpack/jpm#458
>Will try with the API
>Still, stupid :S

hopefully it will be fixed, as guy just assigned this issue.

**Comment by jenslody** [comment]
I have the same behviour with 0.12.4+ and 0.12.3 on Fedora 23 64bit with FF 44.
Collapsing an expanded group from the context-menu works, but auto-collapsing leads to "+"-signs on (almost) all tabs of a group, but not collapsing the groups(s).
I will check with IceCat (based on FF38 esr) later.

**Comment by PikachuEXE** [comment]
I guess I will wait for next ESR (45) before trying to fix it
Since I have no idea what changed and what will be changed again that might cause this issue

**Comment by PikachuEXE** [comment]
Seem no problem to me with 45.0.1 with 0.12.7
WIth auto-collapsing enabled

**Comment by PikachuEXE** [comment]
[tab_kit_2nd_edition_beta-0.12.7-dev-20160404-1106-fx.zip](https://github.com/tabkit/tabkit2/files/201696/tab_kit_2nd_edition_beta-0.12.7-dev-20160404-1106-fx.zip)
This is 0.12.7 with old hack for collaped group removed
Try it
It's signed (finally got it working)

**Comment by M3Rocket** [comment]
Hmmmm. Installed 0.12.7 on 45.0.1 and both 0.12.6 and 0.12.7 stayed enabled. But it still doesn't work for me--weird behavior where all the groups are OPENED upon startup. Disabled 0.12.6, restarted FF and still same problem. So I disabled 0.12.7 and enabled 0.12.6, and it seems now it's working again. 

I'm uninstalling 0.12.7 for now and keep experimenting.

**Comment by PikachuEXE** [comment]
@M3Rocket 
Forgot to say that the original one should be disabled 
Since I need to change ID of the extension and setup another extension to enable auto signing :S

**Comment by M3Rocket** [comment]
Tested 0.12.7-beta more. It seems like it fixes Issue https://github.com/tabkit/tabkit2/issues/71 with the hidden tabs now all showing fine, but creates a different problem with auto-expand/-collapse. Specifically, auto-collapse doesn't seem to work properly. 

1. On startup, all groups are auto-expanded with correct group coloring, but all grouped tabs show the "+" for expand.
2. Selecting a tab within a group removes all the "+" for that group of tabs, which kinda fixes 1.
3. Double-clicking on a tab within the group auto-collapses it.
4. Selecting any tab after a group is auto-collapsed expands that group again and results in 1.

I think you are very close to fixing this!

BTW--just like 0.12.6, this 0.12.7-beta breaks drag and drop Issue https://github.com/tabkit/tabkit2/issues/108

**Comment by PikachuEXE** [comment]
You guys are using different OS (non Windows)?

**Comment by PikachuEXE** [comment]
I have no such problem o_0
What OS are you using? (I am using Win7

**Comment by M3Rocket** [comment]
I am using Windows 7, but your hint helped me solve the problem! 

I was using Tab Groups 1.0.2 to enable Panorama mode because of Issue https://github.com/tabkit/tabkit2/issues/71. I disabled Tab Groups, and now TK2 0.12.7-beta auto-expand/-collapse is fully working!

Although I still can't drag and drop.

**Comment by PikachuEXE** [comment]
Good to hear!
Please see my comment for drag and drop in #108

**Comment by PikachuEXE** [comment]
I removed the old workaround AGAIN 
https://addons.mozilla.org/en-US/firefox/addon/tabkit-2nd-edition/versions/?page=1#version-0.12.8

Let me know the details if you can reproduce the issue
(or if you cannot reproduce it I am happy to hear it)

**Comment by M3Rocket** [comment]
This issue is fixed on all of my setups with 0.12.8 and 0.12.9 in FF46. THANK YOU! Closing.
