### ISSUE TITLE
Tab Groups removed from FF 45.x

### ISSUE THREAD

**Issue by M3Rocket** [tabkit/tabkit2#98]
Just saw the warning in FF 44.0 when using Panorama mode that Tab Groups will be removed in the next major version of FF.

There is an add-on called Tab Groups that is based on FF code: [https://addons.mozilla.org/firefox/addon/tab-groups-panorama/](url)

I've downloaded and tested it, so far, TK2 seems to work with it just the same. However, in the future, not sure whether TK2 will need Tab Groups to operate properly?

**Comment by PikachuEXE** [comment]
No, TK2's group does **not** depend on FF's Tab Groups (actually I remember they are incompatible, not sure)

**Comment by M3Rocket** [comment]
Alright--cool! I'll close it. I was concerned because I'm dependent on Panorama mode to workaround bug https://github.com/tabkit/tabkit2/issues/71
