### ISSUE TITLE
Enter key does not work in address bar when installed

### ISSUE THREAD

**Issue by darnkitten** [tabkit/tabkit2#99]
In Pale Moon 25.8.1 (x64), and Firefox 43.0.4 (x64), the installation of Tabkit2 0.12.4 immediately results in the disabling of the <enter> key in the address/location/URL bar. Uninstallation fixes the problem. Hardware acceleration is unchecked.

This has happened before with other extensions:
https://bugzilla.mozilla.org/show_bug.cgi?id=376084
https://bugzilla.mozilla.org/show_bug.cgi?id=475653
http://forums.mozillazine.org/viewtopic.php?f=38&t=2418749

----------------------------------

Oh, BTW, selecting the option to put the vertical tabs on the right puts them on the left, and selecting left puts them on the right.

**Comment by darnkitten** [comment]
I don't know what happened with the last link--it was supposed to be the same as the others.

**Comment by PikachuEXE** [comment]
Sorry, only ESR versions supported
You can reopen this if the issue can be reproduced by ESR versions
